name: KRPG
description: Kurogoma4D's Playground.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^0.14.0+3
  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.2
  json_serializable: ^4.1.3
  vsync_provider: ^0.5.0
  image_picker: ^0.8.1+1
  flutter_inappwebview: ^5.3.2
  extended_image: ^4.1.0
  image: ^3.0.2
  infinite_listview: ^1.1.0
  sensors_plus: ^1.0.2

dev_dependencies:
  pedantic_mono: ^1.12.1
  build_runner: ^2.0.5
  freezed: ^0.14.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/starry_sky.flr
